import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./components/Providers";
import HeaderSite from "./components/HeaderSite";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <HeaderSite />
          {children}
        </Providers>
      </body>
    </html>
  );
}
