import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./components/Providers";
import HeaderSite from "./components/HeaderSite";
import BgDark from "@/components/bg-dark";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <Providers>
          <BgDark>
            <HeaderSite />
            {children}
            <Footer />
          </BgDark>
        </Providers>
      </body>
    </html>
  );
}
